version: "2"

linters:
  default: none
  enable:
    - logs

  settings:
    custom:
      logs:
        type: module
        description: "Custom linter for validating log records structure and format"
        original-url: github.com/lazarevFedor/log_records_linter
        settings:
          config: configs/config_rules.json